### PR TITLE
Feature: bash/zsh completion magic

### PR DESCRIPTION
**Pull request by SchnWalter**
:tada:

### CODE REVIEW

**Comment by patcon** [comment]
Coolio.

I'm getting this on Ubuntu 14.04 with zsh:

```
~/repos/mission-impossible-android (SchnWalter-feature/bash-autocomplete ✘)✭ ᐅ source mia/mia.bash_completion.sh 
mia/mia.bash_completion.sh:96: command not found: complete
```

**Comment by patcon** [comment]
Ah, seems it's bash-only. Work for me in bash. Perhaps check the shell when it's being sourced, and raise a warning and bail if not bash or other compat shell?

**Comment by SchnWalter** [comment]
Never used Zsh before... I kind of like the completion functionality (but it is a pain to implement) -- And of course, as always, there is never enough documentation :D

**Comment by SchnWalter** [comment]
The scripts could still use some improvement, but it should be enough for now.

Please note that multil-ine descriptions for options and commands should end in ` \` for the descriptions in the Zsh completion to work properly. (see the `-e :a` option for the `sed` command)

**Comment by patcon** [comment]
Good call :) Sorry this got lost

**Pull request merged**
